# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='标签'),
        ),
    ]
