# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authuser_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='账户余额'),
        ),
    ]
