# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 11:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audittype', models.CharField(max_length=20, null=True, verbose_name='审核类型')),
                ('certificate', models.CharField(blank=True, max_length=200, null=True, verbose_name='凭证')),
                ('status', models.IntegerField(null=True, verbose_name='审核状态 0:审核不通过 1:审核通过 2:待审核')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('audit_time', models.DateTimeField(null=True, verbose_name='审核时间')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'db_table': 'f_audit',
            },
        ),
        migrations.CreateModel(
            name='FOrder',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='订单号')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='总金额(元)')),
                ('paytype', models.CharField(blank=True, max_length=20, null=True, verbose_name='支付方式')),
                ('transaction_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='第三方交易号')),
                ('orderstatus', models.IntegerField(blank=True, choices=[(0, '未支付'), (1, '已支付'), (2, '已退款')], null=True, verbose_name='订单状态')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='下单时间')),
                ('paytime', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'f_orders',
            },
        ),
        migrations.CreateModel(
            name='FWalletBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('billtype', models.CharField(blank=True, max_length=20, null=True, verbose_name='账单类型')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='账单金额(元)')),
                ('paytype', models.CharField(blank=True, max_length=20, null=True, verbose_name='支付方式')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='账号余额')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FOrder', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'f_walletbills',
            },
        ),
        migrations.CreateModel(
            name='FWithDraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='实际到账金额')),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='手续费')),
                ('platform', models.CharField(blank=True, max_length=20, null=True, verbose_name='到账平台')),
                ('status', models.IntegerField(null=True, verbose_name='提现状态 1:提现成功 2:提现中 3:已退款')),
                ('transaction_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='第三方交易号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('achieve_time', models.DateTimeField(verbose_name='完成时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FOrder', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '提现',
                'verbose_name_plural': '提现',
                'db_table': 'f_withdraws',
            },
        ),
        migrations.AddField(
            model_name='faudit',
            name='withdraw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.FWithDraw', verbose_name='提现'),
        ),
    ]
