# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20170323_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='faccountaudit',
            name='transfer_account',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='收款账户'),
        ),
        migrations.AlterField(
            model_name='faccountaudit',
            name='certificate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='充值凭证'),
        ),
    ]
