# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_auto_20170323_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAccountTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfertype', models.CharField(max_length=20, null=True, verbose_name='交易类型')),
                ('certificate', models.CharField(blank=True, max_length=200, null=True, verbose_name='充值凭证')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='金额')),
                ('transfer_account', models.CharField(blank=True, max_length=200, null=True, verbose_name='收款账户')),
                ('status', models.IntegerField(null=True, verbose_name='审核状态 0:审核不通过 1:审核通过 2:待审核')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('audit_time', models.DateTimeField(null=True, verbose_name='审核时间')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('withdraw', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.FWithDraw', verbose_name='提现')),
            ],
            options={
                'db_table': 'f_account_transfer',
            },
        ),
        migrations.RemoveField(
            model_name='faccountaudit',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='faccountaudit',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='faccountaudit',
            name='withdraw',
        ),
        migrations.DeleteModel(
            name='FAccountAudit',
        ),
    ]
