# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20170323_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fwithdraw',
            name='order',
        ),
        migrations.RemoveField(
            model_name='fwithdraw',
            name='user',
        ),
        migrations.RemoveField(
            model_name='faccounttransfer',
            name='withdraw',
        ),
        migrations.DeleteModel(
            name='FWithDraw',
        ),
    ]
