# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20170323_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='forder',
            name='relateobj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='关联对象'),
        ),
        migrations.AddField(
            model_name='forder',
            name='transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.FAccountTransfer', verbose_name='关联交易'),
        ),
        migrations.AlterField(
            model_name='forder',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 23, 17, 21, 22, 840555), null=True, verbose_name='下单时间'),
        ),
    ]
