# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20170323_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAccountTransfer',
            new_name='FAccountTransferAudits',
        ),
        migrations.AlterField(
            model_name='forder',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='forder',
            name='orderstatus',
            field=models.IntegerField(blank=True, choices=[(0, '未支付'), (1, '已支付'), (2, '已退款'), (3, '交易成功'), (4, '交易关闭')], null=True, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='fwalletbill',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterModelTable(
            name='faccounttransferaudits',
            table='f_account_transfer_audits',
        ),
    ]
