# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default='0ad84a140ed311e79aeac3088f08b8fe', max_length=40, primary_key=True, serialize=False)),
                ('bid', models.IntegerField(null=True, verbose_name='商家id')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户名')),
                ('address', models.CharField(blank=True, default='', max_length=130, null=True, verbose_name='地址')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('wechatName', models.CharField(blank=True, max_length=20, null=True, verbose_name='微信名')),
                ('wechat', models.CharField(blank=True, max_length=20, null=True, verbose_name='微信号')),
                ('qq', models.CharField(blank=True, max_length=13, null=True, verbose_name='qq')),
                ('alipay', models.CharField(blank=True, max_length=20, null=True, verbose_name='alipay')),
                ('bankName', models.CharField(choices=[('zsbank', '招商银行'), ('zgbank', '中国银行'), ('jsbank', '建设银行'), ('gsbank', '工商银行'), ('nybank', '农业银行'), ('jtbank', '交通银行')], max_length=9, null=True, verbose_name='银行')),
                ('bankID', models.CharField(blank=True, max_length=20, null=True, verbose_name='银行')),
                ('realname', models.CharField(blank=True, max_length=20, null=True, verbose_name='真名')),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='标签')),
                ('image', models.ImageField(default='image/default.png', null=True, upload_to='image/Userimage/%Y/%m')),
                ('referrercode', models.CharField(blank=True, max_length=40, null=True, verbose_name='推荐号')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
