# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20170322_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
